//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomaAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Operators = new HashSet<Operator>();
        }
    
        public int CategoryID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Operator> Operators { get; set; }
    }
}
