//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomaAuto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GreenBox_GreenBoxEntities : DbContext
    {
        public GreenBox_GreenBoxEntities()
            : base("name=GreenBox_GreenBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Saler> Salers { get; set; }
        public virtual DbSet<SalersPart> SalersParts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CarCategory> CarCategories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Seller_Order> Seller_Order { get; set; }
        public virtual DbSet<Transmision> Transmisions { get; set; }
    }
}
