//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomaAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public int OperatorID { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public int CategoryID { get; set; }
        public string Password { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
