//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomaAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saler
    {
        public Saler()
        {
            this.SalersParts = new HashSet<SalersPart>();
            this.Seller_Order = new HashSet<Seller_Order>();
        }
    
        public int SalerID { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int CityID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<SalersPart> SalersParts { get; set; }
        public virtual ICollection<Seller_Order> Seller_Order { get; set; }
        public virtual City City { get; set; }
    }
}
