//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomaAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalersPart
    {
        public int SalersPartID { get; set; }
        public Nullable<int> Helped { get; set; }
        public Nullable<int> DontHelped { get; set; }
        public int SalerID { get; set; }
        public Nullable<int> CarModelsID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> CarCategoryID { get; set; }
        public Nullable<int> CarTransmissionID { get; set; }
        public string Note { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual CarModel CarModel1 { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Saler Saler { get; set; }
        public virtual CarCategory CarCategory { get; set; }
        public virtual Transmision Transmision { get; set; }
    }
}
