//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomaAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller_Order
    {
        public int SellerOrderID { get; set; }
        public int SellerID { get; set; }
        public int OrderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Saler Saler { get; set; }
    }
}
